baseURL: https://intro-to-data-science-template.github.io/intro_to_data_science_reader/
languageCode: en-US
defaultContentLanguage: en
title: Intro to Data Science
theme: hugo-theme-learn
metaDataFormat: yaml
defaultContentLanguageInSubdir: no
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  author: Jared Joseph
  customMermaidURL: https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js
  description: Intro to Data Science Course Reader
  disableBreadcrumb: no
  disableLandingPageButton: yes
  disableMermaid: no
  disableNextPrev: yes
  editURL: https://github.com/Intro-to-Data-Science-Template/intro_to_data_science_reader/blob/main/content
  showVisitedLinks: yes
  titleSeparator: '::'
  themeVariant: mine
  landingPageURL: /intro_to_data_science_reader/
outputs:
  home:
    - HTML
    - RSS
    - JSON
Languages:
  en:
    landingPageName: <i class='fas fa-home'></i> Home
    landingPageURL: /intro_to_data_science_reader/
    languageName: English
    menu:
      shortcuts:
        - identifier: ds
          name: <i class='fab fa-fw fa-github'></i> Reader repo
          url: https://github.com/Intro-to-Data-Science-Template
          weight: 10
        - name: <i class='fas fa-fw fa-bullhorn'></i> Credits
          url: /credits
          weight: 30
    #title: ""
    weight: 1
